name: CI

on:
  - push
  - pull_request

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install tox
      - run: tox -e docs

  pep8:
    name: pep8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install tox
      - run: tox -e pep8

  tests:
    name: tests / Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - 'pypy3'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install tox
      - run: tox -e py
